"""The named ABI groups shared by the glibc scripts.

glibc-tools.py takes them as configuration lists to build ("linux" builds
most of the supported Linux ABIs) and glibc-dev.py takes them as --abi
arguments naming the build trees those builds leave behind.
"""

SPECIAL_LISTS = {
  # Most of the supported Linux ABIs
  "linux" : [
    "aarch64-linux-gnu",
    "alpha-linux-gnu",
    "arc-linux-gnuhf",
    "armv7a-linux-gnueabihf",
    "csky-linux-gnuabiv2",
    "hppa-linux-gnu",
    "i686-linux-gnu",
    "loongarch64-linux-gnuf64",
    "loongarch32-linux-gnuf64"
    "m68k-linux-gnu",
    "microblaze-linux-gnu",
    "mips64el-linux-gnu",
    "mips64el-n32-linux-gnu",
    "mipsel-linux-gnu",
    "or1k-linux-gnu-soft",
    "powerpc64le-linux-gnu",
    "powerpc64-linux-gnu",
    "powerpc-linux-gnu-power4",
    "riscv32-linux-gnu-rv32imafdc-ilp32d",
    "riscv64-linux-gnu-rv64imafdc-lp64d",
    "s390x-linux-gnu",
    "sh4-linux-gnu",
    "sparc64-linux-gnu",
    "sparcv9-linux-gnu",
    "x86_64-linux-gnu",
    "x86_64-linux-gnu-x32",
  ],

  # All support triple ABIs with *.abilist (used to update-abi command).
  "abi" : [
    "aarch64-linux-gnu",
    "alpha-linux-gnu",
    "arc-linux-gnuhf",
    "arm-linux-gnueabihf",
    "armeb-linux-gnueabihf",
    "armv7a-linux-gnueabihf",
    "csky-linux-gnuabiv2",
    "hppa-linux-gnu",
    "i686-linux-gnu",
    "loongarch32-linux-gnuf64",
    "loongarch64-linux-gnuf64",
    "m68k-linux-gnu",
    "m68k-linux-gnu-coldfire",
    "microblaze-linux-gnu",
    "microblazeel-linux-gnu",
    "mips64el-linux-gnu",
    "mips64el-n32-linux-gnu",
    "mipsel-linux-gnu",
    "mips-linux-gnu-soft",
    "or1k-linux-gnu-soft",
    "powerpc64le-linux-gnu",
    "powerpc64-linux-gnu",
    "powerpc-linux-gnu",
    "powerpc-linux-gnu-power4",
    "powerpc-linux-gnu-soft",
    "riscv32-linux-gnu-rv32imafdc-ilp32d",
    "riscv64-linux-gnu-rv64imafdc-lp64d",
    "s390x-linux-gnu",
    "sh4-linux-gnu",
    "sh4eb-linux-gnu",
    "sparc64-linux-gnu",
    "sparcv9-linux-gnu",
    "x86_64-linux-gnu",
    "x86_64-linux-gnu-x32",

    "i686-gnu",
    "x86_64-gnu",
  ],

  "abi32" : [
    "arm-linux-gnueabihf",
    "armeb-linux-gnueabihf",
    "csky-linux-gnuabiv2",
    "hppa-linux-gnu",
    "i686-linux-gnu",
    "m68k-linux-gnu",
    "m68k-linux-gnu-coldfire",
    "microblaze-linux-gnu",
    "microblazeel-linux-gnu",
    "mips64-n32-linux-gnu",
    "mips-linux-gnu",
    "mips-linux-gnu-soft",
    #"nios2-linux-gnu",
    "or1k-linux-gnu-soft",
    "powerpc-linux-gnu",
    "powerpc-linux-gnu-soft",
    "sh4-linux-gnu",
    "sh4eb-linux-gnu",
    "sparcv9-linux-gnu",
  ],

  "powerpc64le" : [
    "powerpc64le-linux-gnu",
    "powerpc64le-linux-gnu-disable-multi-arch",
    "powerpc64le-linux-gnu-power10",
    "powerpc64le-linux-gnu-power9",
    "powerpc64le-linux-gnu-power8",
    "powerpc64le-linux-gnu-power10-disable-multi-arch",
    "powerpc64le-linux-gnu-power9-disable-multi-arch",
    "powerpc64le-linux-gnu-power8-disable-multi-arch",
  ],

  "powerpc64": [
    "powerpc64-linux-gnu-power8",
    "powerpc64-linux-gnu-power7",
    "powerpc64-linux-gnu-power6x",
    "powerpc64-linux-gnu-power6",
    "powerpc64-linux-gnu-power5+",
    "powerpc64-linux-gnu-power5",
    "powerpc64-linux-gnu-power4",
    "powerpc64-linux-gnu-power8-disable-multi-arch",
    "powerpc64-linux-gnu-power7-disable-multi-arch",
    "powerpc64-linux-gnu-power6x-disable-multi-arch",
    "powerpc64-linux-gnu-power6-disable-multi-arch",
    "powerpc64-linux-gnu-power5+-disable-multi-arch",
    "powerpc64-linux-gnu-power5-disable-multi-arch",
    "powerpc64-linux-gnu-power4-disable-multi-arch",
    "powerpc64-linux-gnu",
    "powerpc64-linux-gnu-disable-multi-arch",
  ],

  "powerpc": [
    "powerpc-linux-gnu-power8",
    "powerpc-linux-gnu-power7",
    "powerpc-linux-gnu-power6x",
    "powerpc-linux-gnu-power6",
    "powerpc-linux-gnu-power5+",
    "powerpc-linux-gnu-power5",
    "powerpc-linux-gnu-power4",
    "powerpc-linux-gnu-power8-disable-multi-arch",
    "powerpc-linux-gnu-power7-disable-multi-arch",
    "powerpc-linux-gnu-power6x-disable-multi-arch",
    "powerpc-linux-gnu-power6-disable-multi-arch",
    "powerpc-linux-gnu-power5+-disable-multi-arch",
    "powerpc-linux-gnu-power5-disable-multi-arch",
    "powerpc-linux-gnu-power4-disable-multi-arch",
    "powerpc-linux-gnu",
  ],

  "zseries": [
    "s390x-linux-gnu",
    "s390x-linux-gnu-disable-multi-arch",
    "s390x-linux-gnu-z10",
    "s390x-linux-gnu-z196",
    "s390x-linux-gnu-z900",
    "s390x-linux-gnu-z13",
  ],

  "arm": [
     "arm-linux-gnueabi",
     "arm-linux-gnueabihf",
     "armv5-linux-gnueabihf",
     "armv6-linux-gnueabihf",
     "armv6t2-linux-gnueabihf",
     "armv7a-linux-gnueabi",
     "armv7a-linux-gnueabihf",
     "armv7a-linux-gnueabihf-disable-multi-arch",
     "armv7a-neon-linux-gnueabihf",
     "armv7a-neonvfpv4-linux-gnueabihf",
     "armv7a-neonhard-linux-gnueabihf",
     "armv7a-neonhardvpfv4-linux-gnueabihf",
     "armv7a-thumb-linux-gnueabihf",
  ],

  "armeb": [
    "armeb-linux-gnueabihf",
    "armeb-v5-linux-gnueabihf",
    "armeb-v6-linux-gnueabihf",
    "armeb-v6t2-linux-gnueabihf",
    "armeb-v7-linux-gnueabihf",
    "armeb-v7neon-linux-gnueabihf",
    "armeb-v7neonhard-linux-gnueabihf",
  ],

  "sparc": [
    "sparc-linux-gnu",
    "sparc64-linux-gnu",
    "sparc64-linux-gnu-disable-multi-arch",
    "sparcv8-linux-gnu",
    "sparcv9-linux-gnu",
    "sparcv9-linux-gnu-disable-multi-arch",
  ],

  "mips": [
    "mips-linux-gnu",
    "mips-linux-gnu-mips16",
    "mips-linux-gnu-soft",
    "mipsisa32r6el-linux-gnu",
    "mips64-linux-gnu",
    "mips64-n32-linux-gnu",
    "mipsel-linux-gnu",
    "mips64el-linux-gnu",
    "mips64el-n32-linux-gnu",
    "mipsisa64r6el-linux-gnu",
    "mipsisa64r6el-n64-linux-gnu",
  ],

  "x86_64": [
    "x86_64-linux-gnu",
    "x86_64-linux-gnu-disable-multi-arch",
    "x86_64-linux-gnu-v2",
    "x86_64-linux-gnu-v3",
    "x86_64-linux-gnu-v4",
    "x86_64-linux-gnu-x32"
  ],

  "i686": [
    "i486-linux-gnu",
    "i586-linux-gnu",
    "i686-linux-gnu",
    "i686-linux-gnu-disable-multi-arch",
    "i686-linux-gnu-fp",
  ],
}
